# Copyright 2026 Omni Cyber Solutions LLC. Apache License 2.0.
"""
PDF report renderer using ReportLab.

Generates PDF bytes from incident and executive summary data.
Uses reportlab (pure Python, no native deps beyond Pillow) so it works
in the container without system-level libraries.
"""

import io
import logging
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)

# ─── HTML template strings (used as fallback when reportlab unavailable) ─────

_INCIDENT_HTML_TMPL = """\
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Incident Summary — $tenant_id</title>
<style>
  body { font-family: Arial, sans-serif; font-size: 12px; margin: 40px; }
  h1 { color: #c0392b; }
  table { border-collapse: collapse; width: 100%; margin-top: 16px; }
  th, td { border: 1px solid #ccc; padding: 6px 10px; text-align: left; }
  th { background: #2c3e50; color: #fff; }
  tr:nth-child(even) { background: #f2f2f2; }
  .footer { margin-top: 40px; font-size: 10px; color: #888; }
</style>
</head>
<body>
  <h1>OpenClaw Incident Summary</h1>
  <p><strong>Tenant:</strong> $tenant_id &nbsp; <strong>Generated:</strong> $generated_at</p>
  <p><strong>Period:</strong> Last $period_days days &nbsp;
     <strong>Total incidents:</strong> $total</p>
  <table>
    <tr>
      <th>#</th><th>ID</th><th>Severity</th><th>Status</th>
      <th>Rule</th><th>Host</th><th>First Seen</th>
    </tr>
    $rows
  </table>
  <div class="footer">Generated by OpenClaw Platform &mdash; Omni Cyber Solutions LLC</div>
</body>
</html>
"""

_EXECUTIVE_HTML_TMPL = """\
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Executive Summary — $tenant_id</title>
<style>
  body { font-family: Arial, sans-serif; font-size: 13px; margin: 48px; }
  h1 { color: #2c3e50; }
  h2 { color: #c0392b; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
  .metric { display: inline-block; margin: 8px 24px 8px 0; }
  .metric .val { font-size: 32px; font-weight: bold; color: #2c3e50; }
  .metric .lbl { font-size: 11px; color: #888; }
  table { border-collapse: collapse; width: 100%; margin-top: 12px; }
  th, td { border: 1px solid #ccc; padding: 6px 10px; }
  th { background: #2c3e50; color: #fff; }
  .footer { margin-top: 40px; font-size: 10px; color: #888; }
</style>
</head>
<body>
  <h1>OpenClaw Security Executive Summary</h1>
  <p><strong>Tenant:</strong> $tenant_id &nbsp;
     <strong>Period:</strong> Last $period_days days &nbsp;
     <strong>Generated:</strong> $generated_at</p>
  <h2>Key Metrics</h2>
  <div>
    <div class="metric"><div class="val">$total_incidents</div><div class="lbl">Total Incidents</div></div>
    <div class="metric"><div class="val">$critical_count</div><div class="lbl">Critical</div></div>
    <div class="metric"><div class="val">$high_count</div><div class="lbl">High</div></div>
    <div class="metric"><div class="val">$open_count</div><div class="lbl">Open</div></div>
    <div class="metric"><div class="val">$resolved_count</div><div class="lbl">Resolved</div></div>
  </div>
  <h2>Severity Breakdown</h2>
  <table>
    <tr><th>Severity</th><th>Count</th></tr>
    $severity_rows
  </table>
  <h2>Top Triggered Rules</h2>
  <table>
    <tr><th>Rule</th><th>Hits</th></tr>
    $rule_rows
  </table>
  <div class="footer">Generated by OpenClaw Platform &mdash; Omni Cyber Solutions LLC</div>
</body>
</html>
"""


def _html_incident_rows(incidents: list[dict[str, Any]]) -> str:
    rows = []
    for i, inc in enumerate(incidents, 1):
        first_seen = inc.get("first_seen_at", "")
        if hasattr(first_seen, "isoformat"):
            first_seen = first_seen.isoformat()
        rows.append(
            f"<tr><td>{i}</td>"
            f"<td>{inc.get('id', '')}</td>"
            f"<td>{inc.get('severity', '')}</td>"
            f"<td>{inc.get('status', '')}</td>"
            f"<td>{inc.get('rule_name', '')}</td>"
            f"<td>{inc.get('hostname', '')}</td>"
            f"<td>{first_seen}</td></tr>"
        )
    return "\n".join(rows)


def _substitute(template: str, values: dict[str, Any]) -> str:
    """Simple $key substitution without importing string.Template to avoid shadowing."""
    result = template
    for key, val in values.items():
        result = result.replace(f"${key}", str(val))
    return result


def _render_pdf_with_reportlab(html: str) -> bytes:
    """
    Convert HTML to a minimal PDF using ReportLab.
    We render a simplified plain-text representation inside a PDF since
    ReportLab does not parse HTML directly (that requires xhtml2pdf/weasyprint).
    For a full HTML→PDF pipeline integrate xhtml2pdf as an optional dep.
    """
    try:
        from reportlab.lib.pagesizes import A4  # type: ignore[import-untyped]
        from reportlab.lib.styles import getSampleStyleSheet  # type: ignore[import-untyped]
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer  # type: ignore[import-untyped]
        from reportlab.lib.units import cm  # type: ignore[import-untyped]
    except ImportError:
        logger.warning(
            "reportlab not installed — returning HTML bytes with PDF MIME type stub"
        )
        return html.encode("utf-8")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=2 * cm, rightMargin=2 * cm)
    styles = getSampleStyleSheet()
    story = []

    # Strip HTML tags for plain-text PDF rendering
    import re

    text = re.sub(r"<[^>]+>", " ", html)
    text = re.sub(r"\s+", " ", text).strip()

    for chunk in [text[i : i + 2000] for i in range(0, len(text), 2000)]:
        story.append(Paragraph(chunk, styles["Normal"]))
        story.append(Spacer(1, 0.3 * cm))

    doc.build(story)
    return buf.getvalue()


async def render_incident_summary(
    incidents: list[dict[str, Any]],
    tenant_id: str,
    period_days: int = 30,
) -> bytes:
    """
    Render an incident summary report.
    Returns PDF bytes (or HTML bytes if reportlab is unavailable).
    """
    generated_at = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    html = _substitute(
        _INCIDENT_HTML_TMPL,
        {
            "tenant_id": tenant_id,
            "generated_at": generated_at,
            "period_days": period_days,
            "total": len(incidents),
            "rows": _html_incident_rows(incidents),
        },
    )
    return _render_pdf_with_reportlab(html)


async def render_executive_summary(
    data: dict[str, Any],
    tenant_id: str,
) -> bytes:
    """
    Render an executive summary report.
    `data` should contain keys: incidents (list), period_days (int).
    Returns PDF bytes (or HTML bytes if reportlab is unavailable).
    """
    incidents: list[dict[str, Any]] = data.get("incidents", [])
    period_days: int = data.get("period_days", 30)

    from collections import Counter

    severity_counter: Counter[str] = Counter(
        inc.get("severity", "UNKNOWN") for inc in incidents
    )
    rule_counter: Counter[str] = Counter(
        inc.get("rule_name", "unknown") for inc in incidents
    )
    status_counter: Counter[str] = Counter(
        inc.get("status", "UNKNOWN") for inc in incidents
    )

    severity_rows = "\n".join(
        f"<tr><td>{sev}</td><td>{cnt}</td></tr>"
        for sev, cnt in severity_counter.most_common()
    )
    rule_rows = "\n".join(
        f"<tr><td>{rule}</td><td>{cnt}</td></tr>"
        for rule, cnt in rule_counter.most_common(10)
    )

    generated_at = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    html = _substitute(
        _EXECUTIVE_HTML_TMPL,
        {
            "tenant_id": tenant_id,
            "generated_at": generated_at,
            "period_days": period_days,
            "total_incidents": len(incidents),
            "critical_count": severity_counter.get("CRITICAL", 0),
            "high_count": severity_counter.get("HIGH", 0),
            "open_count": status_counter.get("OPEN", 0),
            "resolved_count": status_counter.get("RESOLVED", 0),
            "severity_rows": severity_rows,
            "rule_rows": rule_rows,
        },
    )
    return _render_pdf_with_reportlab(html)
